version: "3"
services:
  zookeeper:  # the configuration manager
    hostname: auth-geous.sntglobal.net
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    restart: always      
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888
    healthcheck:
      test: "exit 0"      
    networks:
      - prod-network      
  nifi2:
    hostname: auth-geous.sntglobal.net
    container_name: nifi2
    restart: always    
    image: thaihv/nifi2:0.0.1
    ports:
      - 8443:8443 # Secured HTTP Web Port
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=auth-geous.sntglobal.net
      - NIFI_SECURITY_USER_OIDC_DISCOVERY_URL=https://auth-geous.sntglobal.net/realms/setl-nifi/.well-known/openid-configuration
      - NIFI_SECURITY_USER_OIDC_CLIENT_ID=nifi2
      - NIFI_SECURITY_USER_OIDC_CLIENT_SECRET=3fxvwh8LfcGRVS5sqeAlW7MR5JasYkay
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=oidc-provider
      - NIFI_AUTHORIZER_CONFIGURATION_FILE=conf/authorizers.xml
    healthcheck:
      test: "exit 0"      
    networks:
      - prod-network      
networks:
  prod-network:
    driver: bridge      
