
name: Build & Deployment Apache Nifi2

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest  
    env:
      VERSION: '0.0.1'
      JAVA_VERSION: '21'
    steps:
    - name: Clean Disk to avoid full capability
      run: |
        sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
        sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm || true
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf "/opt/hostedtoolcache"    
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        architecture: x64
        cache: maven
    - name: Install Maven 3.9.9
      run: |
        curl -o apache-maven-3.9.9-bin.tar.gz https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        tar -xzf apache-maven-3.9.9-bin.tar.gz
        sudo mv apache-maven-3.9.9 /usr/local/maven
        echo "MAVEN_HOME=/usr/local/maven" >> $GITHUB_ENV
        echo "/usr/local/maven/bin" >> $GITHUB_PATH
      shell: bash
    - name: Set MAVEN_OPTS for Increased Memory
      run: echo "MAVEN_OPTS=-Xmx2g" >> $GITHUB_ENV      
    - name: Verify Maven Version
      run: mvn --version
    - name: Build with Maven
      run: mvn -T1C clean install -DskipTests
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Docker Build nifi2 Image
      working-directory: ./nifi-docker/dockermaven
      run: mvn -P docker clean install      

    - name: Docker Push nifi2 Image to Docker Hub    
      run: docker push thaihv/nifi2:$VERSION
